### ISSUE TITLE
German: Inconsistent translation, Goldmünze/Goldstücke

### ISSUE THREAD

**Issue by BrigitteMathiak** [powerbf/alphabet-soup#12]
**PLATFORM and OS or BROWSER:**

Windows 11

**DCSS VERSION AND GAME INFORMATION:**

Fix 0.3

**DESCRIPTION:**

gold coin should always be translated the same way, e.g. Goldmünze(n)

**EXTRA FILES:**

![image](https://github.com/user-attachments/assets/fedcbd3c-6070-48b1-bc3d-cd25ff4da2ee)

**Comment by powerbf** [comment]
Which one should we use?

**Comment by BrigitteMathiak** [comment]
Either is fine. But Goldmünze would be my favourite.

**Comment by powerbf** [comment]
Fixed in alphabet_soup-0.27 branch. Standardised on Goldmünze.
