### ISSUE TITLE
[German] Untranslated prompt to learn spell

### ISSUE THREAD

**Issue by BrigitteMathiak** [powerbf/alphabet-soup#13]
**PLATFORM and OS or BROWSER:**

Windows 11 tiles

**DCSS VERSION AND GAME INFORMATION:**

b4

**DESCRIPTION:**

see screenshot, also Y did not work to confirm, only J

**EXTRA FILES:**

![image](https://github.com/user-attachments/assets/dff588b7-de54-4fec-803c-4356fabc69b0)

**Comment by powerbf** [comment]
Fixed the untranslated prompt in alphabet_soup-0.27 branch.

Also modified the code so that English answers are also accepted (unless the key is redefined to mean something else in the target language).
