### ISSUE TITLE
[German] I menu - spells not translated

### ISSUE THREAD

**Issue by BrigitteMathiak** [powerbf/alphabet-soup#14]
**PLATFORM and OS or BROWSER:**

Windows 11 tiles
**DCSS VERSION AND GAME INFORMATION:**

b4
**DESCRIPTION:**

The menu that opens with 'I' does not have the spell names translated. 
**EXTRA FILES:**

![image](https://github.com/user-attachments/assets/ea2732d1-06aa-4dd3-94a3-c3b387415ae7)

**Comment by powerbf** [comment]
Fixed in alphabet_soup-0.27 branch
