### ISSUE TITLE
[German] Skill name too long in German

### ISSUE THREAD

**Issue by BrigitteMathiak** [powerbf/alphabet-soup#15]
**PLATFORM and OS or BROWSER:**

Windows tiles
**DCSS VERSION AND GAME INFORMATION:**

**DESCRIPTION:**

Too long skill names make them overlap in the 'm' menu
**EXTRA FILES:**

![image](https://github.com/user-attachments/assets/f2938321-721e-4201-889a-806323cd99f5)

**Comment by powerbf** [comment]
This is changed to "Unbewaffnet" now
