### ISSUE TITLE
[Windows 11] crash when looking at details of magic items or artefacts from the inventory

### ISSUE THREAD

**Issue by BrigitteMathiak** [powerbf/alphabet-soup#16]
**PLATFORM and OS or BROWSER:**

Windows tiles and console
**DCSS VERSION AND GAME INFORMATION:**

beta 4
**DESCRIPTION:**

Find a magic item or artefact, push i and the appropriate letter of that item -> crash
**EXTRA FILES:**

[crash-Cuplov-20241115-192645.txt](https://github.com/user-attachments/files/17779561/crash-Cuplov-20241115-192645.txt)

**Comment by BrigitteMathiak** [comment]
Also wands

**Comment by powerbf** [comment]
I was unable to reproduce this on Windows 10.

**Comment by BrigitteMathiak** [comment]
I will test it on a different computer next week. On Windows 11, it is very reproducible.

**Comment by powerbf** [comment]
What kind of wand was it?

**Comment by BrigitteMathiak** [comment]
Could no longer reproduce in b4.5

**Comment by powerbf** [comment]
I suspect this was caused by the use of std::regex in localise.cc, which has now been changed to use the regex wrapper, which will use PCRE on WIndows (and the wrapper catches exceptions anyway).
