### ISSUE TITLE
[Windows 11] crashes after dying

### ISSUE THREAD

**Issue by BrigitteMathiak** [powerbf/alphabet-soup#17]
**PLATFORM and OS or BROWSER:**
windows tiles and console

**DCSS VERSION AND GAME INFORMATION:**
beta 4

**DESCRIPTION:**
I die. I get to see the inventory reveal and when I hit escape next, it crashes. 

**EXTRA FILES:**
[crash-Cuddaab-20241115-194518.txt](https://github.com/user-attachments/files/17779798/crash-Cuddaab-20241115-194518.txt)

**Comment by powerbf** [comment]
I was unable to reproduce this on Windows 10.

**Comment by powerbf** [comment]
I suspect this was caused by the use of std::regex in localise.cc, which has now been changed to use the regex wrapper, which will use PCRE on WIndows (and the wrapper catches exceptions anyway).
