### ISSUE TITLE
[German] Wendung schould be Runde

### ISSUE THREAD

**Issue by BrigitteMathiak** [powerbf/alphabet-soup#18]
**PLATFORM and OS or BROWSER:**
windows tiles

**DCSS VERSION AND GAME INFORMATION:**
beta 4

**DESCRIPTION:**

In the '%' menu, but also generally, if there are more Wendungen
**EXTRA FILES:**

![image](https://github.com/user-attachments/assets/07c93e07-f73d-4e23-8ea8-67782e6c79f8)

**Comment by powerbf** [comment]
Fixed in alphabet_soup-0.27 branch
