### ISSUE TITLE
[German] Wiz is not translated in detail view

### ISSUE THREAD

**Issue by BrigitteMathiak** [powerbf/alphabet-soup#28]
**PLATFORM and OS or BROWSER:**

Windows 10

**DCSS VERSION AND GAME INFORMATION:**

b4.5

**DESCRIPTION:**

As title

**EXTRA FILES:**

![image](https://github.com/user-attachments/assets/d2335480-a161-4a44-aa48-8e2711a084c9)

**Comment by powerbf** [comment]
Fixed in alphabet_soup-0.27 branch.

![image](https://github.com/user-attachments/assets/fd0f171a-b99c-455e-8d98-a91ae282f722)
